added support for no username/password
QualiSystemsLab/cloudshell-email pull request #22
Opened 2022-03-17 21:34 UTC by omri-amd

2022-03-21 16:26 UTC, alexazarh requested changes
@omri-amd we need to implement this functionality in a different way.
In the suggested implementation even if one of the user or password props are empty the code will not try to login. It can cause some issues with config validations.
In general using an SMTP relay with no auth is a very bad practice from what I know.
I prefer to add explicit support to something like this so it will be clear that we dont want to use any auth. 
To achieve this lets do the following:
1. Add a prop to the EmailConfig obj called "disable_smtp_auth" with default value of False. 
2. Also need to add a boolean Attribute to the email config shell for this information. Lets call it "Disable SMTP Auth". Default value is False. Please add proper description to this attribute as well.
3. Expand the code in create_from_email_config_resource method to get the value of the new attribute and pass it to EmailConfig
4. In the _login method check the value of "self._email_config.disable_smtp_auth" to decide what to do
5. Increase minor version

2022-03-22 05:29 UTC, omri-amd commented
hi @alexazarh, pushed another commit with the requested changes.
please note, an additional change was made to the shell itself, added the "convert_to_bool" function as the Shell was calling the "EmailConfig" directly (bypassing the "create_from_config_resource" that was in use in the setup/teardown scripts)

2022-03-22 15:15 UTC, alexazarh requested changes
Please also update version of "email-config-shell/shell-definition.yaml" in line 6.
All other changes looks good to me.

2022-03-22 15:33 UTC, alexazarh approved these changes

2022-03-22 15:33 UTC, merged